"""
expedition_regions.py - one expedition per region (generated by
regions_build/make_expedition_regions.py; edit that file, not this one).

Kanto's three bird expeditions live in expedition_data.py. Each of these
needs that region's intro badges and can only be started while you're there.
"""
from .gym_data import GymMon
from .expedition_data import Expedition, Floor

REGION_EXPEDITIONS = [
    Expedition(
        'burned_tower', 'Burned Tower', 'Entei', 244, 4,
        'The burnt-out tower in Ecruteak City. Wild Pokémon nest in the charred halls, and something powerful sleeps in the basement. Water, Ground and Rock types make short work of Entei.',
        [
         Floor('Charred Halls',
               [
                GymMon('Raticate', 23, ['Hyper Fang', 'Assurance', 'Bite', 'Quick Attack']),
                GymMon('Koffing', 23, ['Sludge', 'Clear Smog', 'Assurance', 'Poison Gas']),
                GymMon('Zubat', 23, ['Poison Fang', 'Astonish', 'Absorb'])],
               cash=300),
         Floor('Collapsed Floor',
               [
                GymMon('Golbat', 26, ['Poison Fang', 'Astonish', 'Absorb']),
                GymMon('Magmar', 27, ['Flame Wheel', 'Ember', 'Clear Smog', 'Scary Face'])],
               cash=400),
         Floor('Basement',
               [
                GymMon('Raticate', 29, ['Hyper Fang', 'Crunch', 'Sucker Punch', 'Assurance']),
                GymMon('Houndoom', 30, ['Fire Fang', 'Bite', 'Incinerate', 'Howl']),
                GymMon('Magmar', 30, ['Fire Punch', 'Flame Wheel', 'Ember', 'Scary Face'])],
               cash=500),
         Floor('Entei',
               [GymMon('Entei', 37, ['Fire Fang', 'Stomp', 'Extreme Speed', 'Scary Face'])],
               cash=0, boss=True)],
        region='Johto'),
    Expedition(
        'desert_ruins', 'Desert Ruins', 'Regirock', 377, 4,
        "An ancient chamber sealed in the Route 111 desert. Sand-dwellers guard the dunes; Regirock's defence is rock-hard, so bring Water, Grass, Fighting or Steel types and hit it with special attacks.",
        [
         Floor('Route 111 Dunes',
               [
                GymMon('Sandshrew', 26, ['Bulldoze', 'Swift', 'Rapid Spin', 'Defense Curl']),
                GymMon('Cacnea', 26, ['Payback', 'Bullet Seed', 'Growth', 'Leech Seed']),
                GymMon('Trapinch', 26, ['Bulldoze', 'Bite', 'Sand Tomb', 'Astonish'])],
               cash=300),
         Floor('Sandstorm',
               [
                GymMon('Baltoy', 29, ['Extrasensory', 'Psybeam', 'Cosmic Power', 'Harden']),
                GymMon('Sandslash', 30, ['Bulldoze', 'Swift', 'Rapid Spin', 'Defense Curl'])],
               cash=400),
         Floor('Ancient Chamber',
               [
                GymMon('Sandslash', 32, ['Bulldoze', 'Swift', 'Rapid Spin', 'Defense Curl']),
                GymMon('Solrock', 33, ['Psychic', 'Flare Blitz', 'Morning Sun', 'Cosmic Power']),
                GymMon('Cacturne', 33, ['Payback', 'Bullet Seed', 'Spikes', 'Growth'])],
               cash=500),
         Floor('Regirock',
               [GymMon('Regirock', 40, ['Rock Slide', 'Bulldoze', 'Curse', 'Iron Defense'])],
               cash=0, boss=True)],
        region='Hoenn'),
    Expedition(
        'lake_valor', 'Lake Valor', 'Azelf', 482, 4,
        "The drained lake beside Pastoria City. Team Galactic's Pokémon hold the lakeshore, and Azelf, the Being of Willpower, waits in the cavern. Dark, Ghost and Bug types hit it hard.",
        [
         Floor('Drained Lakebed',
               [
                GymMon('Glameow', 28, ['Fake Out', 'Feint Attack', 'Charm', 'Hypnosis']),
                GymMon('Stunky', 28, ['Venoshock', 'Bite', 'Acid Spray', 'Poison Gas']),
                GymMon('Golbat', 28, ['Air Cutter', 'Poison Fang', 'Astonish', 'Absorb'])],
               cash=300),
         Floor('Galactic Camp',
               [
                GymMon('Bronzor', 31, ['Extrasensory', 'Confusion', 'Payback', 'Hypnosis']),
                GymMon('Croagunk', 32, ['Poison Jab', 'Venoshock', 'Sucker Punch', 'Astonish'])],
               cash=400),
         Floor('Valor Cavern',
               [
                GymMon('Golbat', 34, ['Air Cutter', 'Poison Fang', 'Bite', 'Astonish']),
                GymMon('Skuntank', 35, ['Sucker Punch', 'Venoshock', 'Bite', 'Poison Gas']),
                GymMon('Bronzong', 35, ['Extrasensory', 'Confusion', 'Payback', 'Hypnosis'])],
               cash=500),
         Floor('Azelf',
               [GymMon('Azelf', 42, ['Extrasensory', 'Tri Attack', 'Nasty Plot', 'Rest'])],
               cash=0, boss=True)],
        region='Sinnoh'),
    Expedition(
        'pinwheel_forest', 'Pinwheel Forest', 'Virizion', 640, 4,
        'The dense forest outside Nacrene City. Bug and Fighting types fill the woods, and Virizion waits in the clearing at its heart. Flying types hit it four times as hard; Fire, Psychic and Poison work too.',
        [
         Floor('Forest Edge',
               [
                GymMon('Sewaddle', 25, ['Bug Bite', 'Razor Leaf', 'Struggle Bug', 'String Shot']),
                GymMon('Venipede', 25, ['Venoshock', 'Bug Bite', 'Poison Tail', 'Defense Curl']),
                GymMon('Cottonee', 25, ['Giga Drain', 'Razor Leaf', 'Fairy Wind', 'Growth'])],
               cash=300),
         Floor('Deep Woods',
               [
                GymMon('Throh', 28, ['Revenge', 'Circle Throw', 'Bind', 'Bulk Up']),
                GymMon('Sawk', 29, ['Low Sweep', 'Rock Smash', 'Double Kick', 'Bulk Up'])],
               cash=400),
         Floor('Rumination Field',
               [
                GymMon('Whimsicott', 31, ['Giga Drain', 'Razor Leaf', 'Growth', 'Leech Seed']),
                GymMon('Leavanny', 32, ['Bug Bite', 'Razor Leaf', 'Fell Stinger', 'String Shot']),
                GymMon('Scolipede', 32, ['Venoshock', 'Bug Bite', 'Defense Curl', 'Iron Defense'])],
               cash=500),
         Floor('Virizion',
               [GymMon('Virizion', 39, ['Giga Drain', 'Double Kick', 'Take Down', 'Work Up'])],
               cash=0, boss=True)],
        region='Unova'),
    Expedition(
        'ruins_of_conflict', 'Ruins of Conflict', 'Tapu Koko', 785, 3,
        "The ruins of Melemele Island's guardian deity. Electric types crackle along the path. Ground types shrug off Tapu Koko's lightning; Poison and Steel hit it hard.",
        [
         Floor('Melemele Meadow',
               [
                GymMon('Toucannon', 37, ['Drill Peck', 'Pluck', 'Echoed Voice', 'Roost']),
                GymMon('Gumshoos', 37, ['Take Down', 'Bite', 'Work Up', 'Scary Face']),
                GymMon('Charjabug', 37, ['X-Scissor', 'Spark', 'Bug Bite', 'String Shot'])],
               cash=300),
         Floor('Ruins Path',
               [
                GymMon('Togedemaru', 40, ['Zing Zap', 'Spark', 'Defense Curl', 'Charge']),
                GymMon('Magneton', 41, ['Discharge', 'Flash Cannon', 'Spark', 'Thunder Shock'])],
               cash=400),
         Floor('Inner Sanctum',
               [
                GymMon('Electivire', 43, ['Discharge', 'Thunder Punch', 'Shock Wave', 'Charge']),
                GymMon('Raichu-Alola', 44, ['Thunderbolt', 'Discharge', 'Agility', 'Nasty Plot']),
                GymMon('Vikavolt', 44, ['Bug Buzz', 'X-Scissor', 'Charge', 'String Shot'])],
               cash=500),
         Floor('Tapu Koko',
               [GymMon('Tapu Koko', 51, ['Discharge', 'Fairy Wind', 'Charge', 'Agility'])],
               cash=0, boss=True)],
        region='Alola'),
    Expedition(
        'grasswither_shrine', 'Grasswither Shrine', 'Wo-Chien', 1001, 4,
        'A shrine sealed with eight ominous stakes. Grass and Poison types creep around it, and Wo-Chien saps the strength of anything nearby. Bug types hit it four times as hard; Fire, Flying and Fairy work too.',
        [
         Floor('Overgrown Trail',
               [
                GymMon('Bramblin', 28, ['Hex', 'Mega Drain', 'Rapid Spin', 'Defense Curl']),
                GymMon('Shroodle', 28, ['Slash', 'Poison Fang', 'U-turn', 'Acid Spray']),
                GymMon('Toedscool', 28, ['Mud Shot', 'Hex', 'Mega Drain', 'Tackle'])],
               cash=300),
         Floor('Withered Grove',
               [
                GymMon('Dolliv', 31, ['Seed Bomb', 'Razor Leaf', 'Mega Drain', 'Growth']),
                GymMon('Capsakid', 32, ['Razor Leaf', 'Zen Headbutt', 'Headbutt', 'Growth'])],
               cash=400),
         Floor('Shrine Gate',
               [
                GymMon('Brambleghast', 34, ['Hex', 'Mega Drain', 'Rapid Spin', 'Defense Curl']),
                GymMon('Grafaiai', 35, ['Poison Jab', 'Slash', 'Poison Fang', 'U-turn']),
                GymMon('Toedscruel', 35, ['Seed Bomb', 'Mud Shot', 'Hex', 'Mega Drain'])],
               cash=500),
         Floor('Wo-Chien',
               [GymMon('Wo-Chien', 42, ['Dark Pulse', 'Mega Drain', 'Leech Seed', 'Stun Spore'])],
               cash=0, boss=True)],
        region='Paldea'),
]
